# Workflow 名称，在 GitHub Actions 页面显示
name: Build Windows Executable

# 何时运行此 workflow
on:
  release:
    types: [published] # 当一个新的 Release 被“发布”时触发
  push:
  

# 定义一个 Job
jobs:
  build-windows:
    # 在 Windows 最新版虚拟机上运行此 Job
    runs-on: windows-latest

    # --- 添加以下 permissions 块 ---
    permissions:
      contents: write # 允许写入内容 (包括 Release Assets)
      releases: write # 允许写入 Release
    # --- 添加结束 ---

    # Job 中的步骤
    steps:
    - name: Checkout code # 步骤名称：拉取代码
      uses: actions/checkout@v4

    - name: Set up Python # 步骤名称：安装 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 指定 Python 版本，3.6 或更高版本通常都可以

    - name: Install dependencies # 步骤名称：安装依赖（PyInstaller）
      run: pip install pyinstaller

    - name: Build executable with PyInstaller # 步骤名称：使用 PyInstaller 打包
      run: |
        pyinstaller --onefile --console network_switcher.py
        if (-not (Test-Path .\dist\network_switcher.exe)) {
            Write-Host "Error: Executable not found in .\dist\" -ForegroundColor Red
            exit 1
        }

    - name: Upload build artifact (for debugging) # 可选步骤：上传构建产物作为 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: network-switcher-build-windows
        path: dist/

    - name: Upload executable to Release # 步骤名称：上传 exe 到 Release
      uses: actions/upload-release-asset@v1
      id: upload-release-asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 提供的 token，用于认证
      with:
        upload_url: ${{ github.event.release.upload_url }} # 从 Release 触发事件中获取上传 URL
        asset_path: ./dist/network_switcher.exe # 要上传的文件路径（在 Runner 上）
        asset_name: network_switcher_windows_x64.exe # 上传到 Release 后显示的文件名
        asset_content_type: application/octet-stream # 标准的可执行文件 MIME 类型
